// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:214b01e0-8bf9-4cc9-83d2-95028040307b',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'giftapp-hosting-mobilehub-1509484063',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd2ff253qz589kx.cloudfront.net',
aws_mobile_analytics_app_id : '3be626dab06045cc93e4497af8acea2a',
aws_project_id : '04b67cfc-b5c4-4d5e-b147-0a227b64e939',
aws_project_name : 'gift-app',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'giftapp-mobilehub-1509484063',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});